WIP: grain settings page
sandstorm-io/sandstorm pull request #3519
Opened 2021-05-02 19:32 UTC by zenhack

This adds a per-grain settings page, which can be accessed by clicking on a new gear icon in the top-bar on the grain page. Right now, it displays any scheduled jobs for the grain and that's it. I don't consider this ready yet, because the design is really *that* bad. I'd like to make this more presentable before we ship it. I also probably want to add a button to cancel background tasks.

The first commit is an unrelated slight refactoring that I was planning on using and then didn't end up needing in the final design -- but I think it's a bit cleaner so I decided to keep it.

Screenshot:

![Screen Shot 2021-05-02 at 15 24 23](https://user-images.githubusercontent.com/883774/116825045-5a486680-ab5b-11eb-97cf-3841b8689321.png)

2021-05-02 19:35 UTC, zenhack commented
Another gripe I have is that right now the gear icon still shows up if you've got the settings open, but it just doesn't do anything. Maybe it should go back to the grain, just so there's some kind of feedback?

2021-05-02 19:57 UTC, ocdtrekkie commented
I'd agree, the buttons for sharing and webkeys tend to toggle on and off if you click on them.

The other high priority visibility item I'd look for here is the granted Powerbox requests, and the ability to revoke them.

Users don't authorize the scheduled tasks, so I imagine we'd just have an on-off toggle to block the app from using that functionality here?

2021-05-02 20:43 UTC, zenhack commented
I implemented the toggle behavior on the gear icon.

I agree wrt powerbox requests & revoking scheduling access altogether, but I also think it's ok to ship a first version of this with limited functionality and then add stuff to it.

Looks like there are some new linter errors I need to hunt down.

2021-05-02 20:49 UTC, ocdtrekkie commented
As far as the styling question, Can we lift the same style sheets used in the admin panel?

The headings and table styling here looks like what we want:
![image](https://user-images.githubusercontent.com/4399499/116827307-ed829b80-ab5d-11eb-9d3f-a8d85419f018.png)

2021-05-02 20:55 UTC, zenhack commented
I think that would make sense.

2021-05-02 22:55 UTC, ocdtrekkie commented
I would also replace "Open Grain" with "Return to Grain" or similar, unless we expect people to navigate straight to the settings. People may feel like they already opened the grain, so I think the language choice there is weird.

2021-05-02 23:01 UTC, zenhack commented
I think I was anticipating adding a button on the grain list, but I'll change it to 'return' at least until I actually do that.

2021-05-03 01:42 UTC, zenhack commented
Alright, I added some basic styling, and also a couple more columns to the table. Screenshot:

![Screen Shot 2021-05-02 at 21 39 51](https://user-images.githubusercontent.com/883774/116835116-1f602600-ab8f-11eb-9a01-ca8bcff8579b.png)

I'm going to mark this as not a draft; there's more we could do but this is no longer at the level where I would be embarrassed if we shipped this.

2021-05-03 02:05 UTC, ocdtrekkie commented
That looks really good. And I'd probably find the next run information pretty useful for troubleshooting and testing.

2021-05-03 17:07 UTC, ocdtrekkie requested changes

2021-05-03 17:07 UTC, ocdtrekkie commented on shell/i18n/en.i18n.json
> +          "anually": "anually",
s/anually/annually x2 here

2021-05-03 17:32 UTC, ocdtrekkie approved these changes

2021-05-06 22:42 UTC, zenhack commented
I made two other tweaks:

- The return to grain button is now styled.
- I added cancel buttons for the tasks in the scheduled tasks table. It felt super weird to me to have a page called settings where you couldn't *do* anything, so I felt like I should implement at least one thing.

Screenshot of the result:

![Screen Shot 2021-05-06 at 18 40 01](https://user-images.githubusercontent.com/883774/117374243-c9df8e00-ae9a-11eb-9b65-d2e3d9cd6601.png)

2021-05-08 03:27 UTC, zenhack commented
Per discussion with @ocdtrekkie on #3522, I backed out the cancel button feature. I'll likely add the toggle as a separate pr stacked on top of this one.

2021-06-12 01:42 UTC, zenhack commented
Merged in changes from master. @kentonv, did you miss this one when making the last release? Would appreciate a review.

2021-06-12 15:09 UTC, kentonv commented
Hmm I could have sworn this wasn't marked ready yet last time, but the history seems to disagree with me. Sorry about that.

Looks great to me!

2021-06-12 15:09 UTC, merged